### PR TITLE
add bear model and migration

### PR DESCRIPTION
**Pull request by EagleC0318**
# why
- For issue #69 
# how
- Add the model and the migration based on the discussion in #44 and the following questionnaire 
image
# test
Check the table is created locally.
image

### CODE REVIEW

**Comment by EagleC0318** [comment]
Actually I have some thoughts between the questionnaire and the table for bear.
1. Based on the questionnaire, we don't know the age for the bear individually.
2. One of the bear table record is a single bear, means the "其他說明" is by bear and the "個體數" would not be stored on the bear table.

**Review by tai271828 — CHANGES_REQUESTED** [review]
Thanks for the contribution. Would you please fix the error of unittest?

+1 to adding this data structure.

**Comment by tai271828** [comment]
Attached the questionnaire FWIW [Final._20220304.pdf](https://github.com/OH-SHOWN/ohshown-backend/files/9020093/Final._20220304.pdf)

**Review by Neilxx — APPROVED** [review]
Fields look good to me!
Thanks @EagleC0318 🥳

**Comment by tai271828** [comment]
Next step: after @EagleC0318 fixes the CI, we will land this PR.

**Comment by EagleC0318** [comment]
CI Fixed. Somehow I forgot to commit the migration file lol.

**Comment by tai271828** [comment]
Thank you man @EagleC0318 . You are awesome!

**Comment by tai271828** [comment]
Deployed to `ohshown.site:8080` and looks good.

**Pull request merged**
